version: "3"

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: api
        ports:
            - "8001:5432"
    server:
        restart: on-failure
        build:
            context: ./server
        ports:
            - "8080:8080"
        environment:
            PORT: 8080        
    web:
        container_name: 'web'
        restart: on-failure
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - .:/client
            - /client/node_modules
        ports:
            - "4200:80"
